design_task:
  description: >
    Prepare a detailed design for the engineer; outline classes and methods.
    Requirements: {requirements}
    IMPORTANT: Output **markdown only** describing the module, classes and functions.
  expected_output: >
    A detailed markdown design file.
  agent: engineering_lead
  output_file: output/{module_name}_design.md


code_task:
  description: >
    Implement the design in a single Python file.
    Requirements: {requirements}
  expected_output: >
    Raw Python code ONLY (no markdown / backticks).
  agent: backend_engineer
  context: [design_task]
  output_file: output/{module_name}


frontend_task:
  description: >
    Write app.py with a minimal Gradio UI showcasing {class_name} from {module_name}.
    Requirements: {requirements}
  expected_output: >
    Raw Python code ONLY.
  agent: frontend_engineer
  context: [code_task]
  output_file: output/app.py


test_task:
  description: >
    Write unit tests for {module_name} in test_{module_name}.
  expected_output: >
    Raw Python code ONLY.
  agent: test_engineer
  context: [code_task]
  output_file: output/test_{module_name}
